function(prevent_intree_builds)
  get_filename_component(srcdir "${CMAKE_SOURCE_DIR}" REALPATH)
  get_filename_component(bindir "${CMAKE_BINARY_DIR}" REALPATH)
  if("${srcdir}" STREQUAL "${bindir}")
    message("")
    message("In-tree builds are not supported.")
    message("Use a build/ directory (preferably not as a subdirectory)")
    message("    mkdir build")
    message("    cd build")
    message("    cmake <OPTIONS> ..")
    message("")
    message(FATAL_ERROR "Stopping build.")
  endif()
endfunction()
