function(disable_intree_builds)
  get_filename_component(srcdir "${CMAKE_SOURCE_DIR}" REALPATH)
  get_filename_component(bindir "${CMAKE_BINARY_DIR}" REALPATH)
  if("${srcdir}" STREQUAL "${bindir}")
    message(NOTICE "")
    message(NOTICE "In-tree builds are not supported.")
    message(NOTICE "It is recommended to use a separate build/ directory")
    message(NOTICE "    cmake -B <build_dir>")
    message(FATAL_ERROR "Aborting generation...")
  endif()
endfunction()
