function(discourage_intree_builds)
  get_filename_component(srcdir "${CMAKE_SOURCE_DIR}" REALPATH)
  get_filename_component(bindir "${CMAKE_BINARY_DIR}" REALPATH)
  if("${srcdir}" STREQUAL "${bindir}")
    message(WARNING "")
    message(WARNING "In-tree builds are highly discouraged and might fail.")
    message(WARNING "It is recommended to use a separate build/ directory (preferably not as a subdirectory)")
    message(WARNING "    cmake -B <build_dir>")
    message(WARNING "Continuing...")
  endif()
endfunction()
